# This playbook prepares images for the Snakemake Ed-DASH course. For EdGe EC2 images,
# just start any number of regular training VMs, and check they exist with:
#
#  $ ansible-inventory --graph --verbose
#
# If other VMs are running then you'll need to do something smarter.
#
- hosts: tag_Role_trainingdash
  become: yes
  become_user: training
  tasks:

    - name: Set alternative password for VNC
      vars:
        passwd: "ed-dash-1307"
      become_user: training
      shell:
        executable: /bin/bash
        chdir: /home/training/.vnc
        cmd: |
             set -euo pipefail
             mv passwd passwd.old
             echo '{{ passwd }}' | /opt/tigervnc/usr/bin/vncpasswd -f > passwd
             chmod 0600 passwd
      args:
        creates: /home/training/.vnc/passwd.old

    - name: Fetch Miniconda Installer
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
        dest: /home/training/Downloads/miniconda3_installer.sh
        mode: '0644'
        checksum: sha256:536817d1b14cb1ada88900f5be51ce0a5e042bae178b5550e62f61e223deae7c

    - name: Run Miniconda Installer
      shell:
        executable: /bin/bash
        chdir: /home/training
        cmd: |
             set -euo pipefail
             rm -rf ~/.conda ~/miniconda3
             bash ./Downloads/miniconda3_installer.sh -b
             source ~/miniconda3/bin/activate
             conda init
        creates: /home/training/.conda/environments.txt

    # I could do a full checkout of the GitHub repo here?
    # No checksum - the file may change
    - name: Download conda env spec
      get_url:
        url: https://raw.githubusercontent.com/carpentries-incubator/snakemake-novice-bioinformatics/gh-pages/files/conda_env_all.yaml
        dest: /home/training/Downloads/snakemake_conda_env.yaml
        mode: '0644'
        backup: yes

    - name: Bootstrap deps into base env
      shell:
        executable: /bin/bash
        chdir: /home/training
        cmd: |
             set -euo pipefail
             source ~/miniconda3/bin/activate
             conda env update -n base --file /home/training/Downloads/snakemake_conda_env.yaml
             snakemake --version
        creates: /home/training/miniconda3/bin/snakemake

    - name: Download the data files
      get_url:
        url: https://ndownloader.figshare.com/files/28531743
        dest: /home/training/Downloads/snakemake_data.tar.gz
        mode: '0644'
        backup: no

    - name: Unpack the data files
      unarchive:
        src: /home/training/Downloads/snakemake_data.tar.gz
        dest: /home/training
        remote_src: yes
        extra_opts: [ --strip-components=1 ]
        creates: /home/training/yeast

    # I didn't realise GG GZipped all the reads. I can probably work with this but for
    # the initial ru-through I'll stick with the unpacked version.
    - name: Fix up the data files
      shell:
        executable: /bin/bash
        chdir: /home/training
        cmd: |
             set -euo pipefail
             cd ~
             gunzip yeast/reads/*.gz
             rm -rf yeast/bams
             rm -f yeast/samples.csv
             rm -f yeast/.*.txt
        creates: /home/training/yeast/reads/ref1_1.fq

{"mode":"full","isActive":false}
